server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: client_id
            client-secret: client_secret
            client-name: Auth Server
            scope: user_info
            provider: custom-provider
            redirect-uri: http://localhost:8082/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/user/principal
            user-name-attribute: name